<?php
// HOME PAGE SLIDER
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_home-page',
		'title' => 'Home Page',
		'fields' => array (
			array (
				'key' => 'field_53d18ed00673f',
				'label' => 'Slider',
				'name' => 'slider',
				'type' => 'repeater',
				'required' => 1,
				'sub_fields' => array (
         array (
						'key' => 'field_53e2780686430',
						'label' => 'image',
						'name' => 'image',
						'type' => 'image',
						'required' => 1,
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
          /*
         array (
          'key' => 'field_53f509c0b7517',
          'label' => 'Shader',
          'name' => 'shader',
          'type' => 'radio',
          'required' => 1,
          'choices' => array (
            'None' => 'None',
            'Blue' => 'Blue',
            'Black' => 'Black',
          ),
          'other_choice' => 0,
          'save_other_choice' => 0,
          'default_value' => 'None',
          'layout' => 'horizontal',
        ),
        */
					array (
						'key' => 'field_53d18eea06740',
						'label' => 'Headline',
						'name' => 'headline',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53d18efe06741',
						'label' => 'Positioning Statement',
						'name' => 'positioning_statement',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53d18f1306742',
						'label' => 'Subhead',
						'name' => 'subhead',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53d18f2006743',
						'label' => 'Call to Action',
						'name' => 'call_to_action',
						'type' => 'repeater',
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_53d1925876912',
								'label' => 'Button label',
								'name' => 'button_label',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53d1926776913',
								'label' => 'Button URL',
								'name' => 'button_url',
								'type' => 'text',
								'instructions' => 'Include "http://',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_53d192d9a4e51',
								'label' => 'Open in a new window?',
								'name' => 'new_window',
								'type' => 'true_false',
								'column_width' => '',
								'message' => '',
								'default_value' => 0,
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-home.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
